# Configuration file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "pypy" # fails to install numpy

addons:
  apt:
    packages:
    - python-dev
    - pkg-config
    - libfreetype6-dev
    - libpng-dev
#   - libpython-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - libatlas-base-dev
#    - python-matplotlib
    - xvfb

before_install:
    - pip install -U pip
#    - mkdir -p ~/.config/matplotlib
#    - |-
#     echo backend : Agg > ~/.config/matplotlib/matplotlibrc

install:
    - python setup.py install

script:
    - xvfb-run python setup.py test
