# Configuration file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - python-dev
    - pkg-config
    - libfreetype6-dev
    - libpng-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - libatlas-base-dev
    - xvfb

before_install:
    - pip install -U pip

install:
    - python setup.py install

script:
    - xvfb-run python setup.py test
